name: Check software version consistency for citation purposes

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [published]

jobs:
  check-version:
    name: Check version consistency
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.12" # required by version-consistency
          cache: 'pip' # optional

      - name: Run version-consistency
        uses: willynilly/version-consistency@v1.0.0
        with:
          event_name: ${{ github.event_name }}
          ref: ${{ github.ref }}
          release_tag: ${{ github.event.release.tag_name }}
          fail_for_missing_file: false

          check_citation_cff: true
          citation_cff_path: CITATION.cff

          check_pyproject_toml: true
          pyproject_toml_path: pyproject.toml

          check_codemeta_json: true
          codemeta_json_path: codemeta.json

          check_zenodo_json: true
          zenodo_json_path: .zenodo.json

          check_package_json: true
          package_json_path: package.json

          check_setup_py: true
          setup_py_path: setup.py
